<?php

/**
 * @file
 * Contains webform_civicrm.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webform_civicrm_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webform_civicrm module.
    case 'help.page.webform_civicrm':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('CiviCRM and Webform integration') . '</p>';
      return $output;

    default:
  }
}
