<?php

namespace Drupal\webform_civicrm\Plugin\WebformElement;

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\Plugin\WebformElement\TextField;
use Drupal\webform\Plugin\WebformElementBase;
use Drupal\webform\WebformSubmissionInterface;

/**
 * Provides a 'textfield' element.
 *
 * @WebformElement(
 *   id = "civicrm_contact",
 *   api =
 *   "https://api.drupal.org/api/drupal/core!lib!Drupal!Core!Render!Element!Textfield.php/class/Textfield",
 *   label = @Translation("CiviCRM Contact"), description =
 *   @Translation("Choose existing contact."), category =
 *   @Translation("CiviCRM"),
 * )
 */
class CivicrmContact extends WebformElementBase {

  /**
   * {@inheritdoc}
   *
   * @see _webform_render_civicrm_contact()
   */
  public function prepare(array &$element, WebformSubmissionInterface $webform_submission = NULL) {
    parent::prepare($element, $webform_submission);
  }

  /**
   * {@inheritdoc}
   *
   * @see _webform_edit_civicrm_contact()
   */
  public function form(array $form, FormStateInterface $form_state) {
    return parent::form($form, $form_state); // TODO: Change the autogenerated stub
  }

  /**
   * {@inheritdoc}
   */
  public function getDefaultProperties() {
    return [
        'name' => '',
        'form_key' => NULL,
        'pid' => 0,
        'weight' => 0,
        'value' => '',
        'required' => 0,
        'extra' => [
          'search_prompt' => '',
          'none_prompt' => '',
          'results_display' => ['display_name'],
          'allow_create' => 0,
          'widget' => 'autocomplete',
          'show_hidden_contact' => 0,
          'unique' => 0,
          'title_display' => 'before',
          'randomize' => 0,
          'description' => '',
          'no_autofill' => [],
          'hide_fields' => [],
          'hide_method' => 'hide',
          'no_hide_blank' => FALSE,
          'submit_disabled' => FALSE,
          'attributes' => [],
          'private' => FALSE,
          'default' => '',
          'default_contact_id' => '',
          'default_relationship' => '',
          'allow_url_autofill' => TRUE,
          'dupes_allowed' => FALSE,
          'filters' => [
            'contact_sub_type' => 0,
            'group' => [],
            'tag' => [],
            'check_permissions' => 1,
          ],
        ],
      ] + parent::getDefaultProperties();
  }

}
